version: '3.5'

networks:
  roach-net:
    driver: bridge

services:

  roach-source-0:
    container_name: roach-source-0
    hostname: roach-source-0
    image: cockroachdb/cockroach:latest
    networks:
      - roach-net
    command: start --logtostderr --insecure

  roach-source-1:
    container_name: roach-source-1
    hostname: roach-source-1
    image: cockroachdb/cockroach:latest
    networks:
      - roach-net
    command: start --logtostderr --insecure --join=roach-source-0
    depends_on:
      - roach-source-0

  roach-source-2:
    container_name: roach-source-2
    hostname: roach-source-2
    image: cockroachdb/cockroach:latest
    networks:
      - roach-net
    command: start --logtostderr --insecure --join=roach-source-0
    depends_on:
      - roach-source-0

  lb:
    container_name: lb
    hostname: lb
    build: ./nginx
    networks:
      - roach-net
    ports:
      - "5432:5432"
      - "8080:8080"
    links:
      - roach-source-0
      - roach-source-1
      - roach-source-2

  generator:
    container_name: generator
    hostname: generator
    build: ./generator
    networks:
      - roach-net
    links:
      - lb

  roach-destination:
    container_name: roach-destination
    hostname: roach-destination
    image: cockroachdb/cockroach:latest
    networks:
      - roach-net
    command: start --logtostderr --insecure
    ports:
      - "8081:8080"
      - "26257:26257"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - roach-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    networks:
      - roach-net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "39092:39092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_A://kafka:29092,LISTENER_B://kafka:9092,LISTENER_C://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_A:PLAINTEXT,LISTENER_B:PLAINTEXT,LISTENER_C:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_A
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1