version: '3.5'

networks:
  roach-net:
    driver: bridge

services:

  roach-0:
    container_name: roach-0
    hostname: roach-0
    image: cockroachdb/cockroach:latest
    networks:
      - roach-net
    command: start --logtostderr --insecure --join=roach-0,roach-1,roach-2

  roach-1:
    container_name: roach-1
    hostname: roach-1
    image: cockroachdb/cockroach:latest
    networks:
      - roach-net
    command: start --logtostderr --insecure --join=roach-0,roach-1,roach-2

  roach-2:
    container_name: roach-2
    hostname: roach-2
    image: cockroachdb/cockroach:latest
    networks:
      - roach-net
    command: start --logtostderr --insecure --join=roach-0,roach-1,roach-2

  lb:
    container_name: lb
    hostname: lb
    build: ./nginx
    networks:
      - roach-net
    ports:
      - "5432:5432"
      - "8080:8080"
    links:
      - roach-0
      - roach-1
      - roach-2

  generator:
    container_name: generator
    hostname: generator
    build: ./generator
    networks:
      - roach-net
    links:
      - lb

  roach-backup:
    container_name: roach-backup
    hostname: roach-backup
    image: cockroachdb/cockroach:latest
    networks:
      - roach-net
    command: start --logtostderr --insecure
    ports:
      - "8081:8080"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - roach-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    networks:
      - roach-net
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1