version: '3.5'

services:

  roach-source:
    container_name: roach-source
    hostname: roach-source
    image: cockroachdb/cockroach:latest
    command: start-single-node --logtostderr=WARNING --insecure
    ports:
      - "8080:8080"
      - "26257:26257"

  roach-destination:
    container_name: roach-destination
    hostname: roach-destination
    image: cockroachdb/cockroach:latest
    command: start-single-node --logtostderr=WARNING --insecure
    ports:
      - "8081:8080"
      - "26258:26257"

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    hostname: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "39092:39092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_A://kafka:29092,LISTENER_B://kafka:9092,LISTENER_C://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_A:PLAINTEXT,LISTENER_B:PLAINTEXT,LISTENER_C:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_A
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1